---
title: "Welcome"
output:
  html_document:
    theme: paper
    highlight: pygments
    toc: false
    toc_float:
      collapsed: false
      smooth_scroll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Language for Statistical Computing in Business Analysis (EXGEN5449)

Hello and welcome to our course website! My name is Stefan Schreiber and I am your course instructor for [EXGEN5449](https://www.ualberta.ca/extension/continuing-education/courses/EXGEN-5449).

In this course, I will provide you with an introduction to the R programming language to perform data manipulation, data visualization and basic statistical analyses. Since this will be an introductory course, you won't need any prior experience in R, however, if you do, it will certainly be helpful. I designed the course to be hands-on, which means I will refrain from providing lecture-type presentations but instead spend time with you writing R code and answer questions as they appear. As with any other language, at first, it may seem impossible to ever get good at it but with time and practice you will become a data science wizard. 

For this course, we will be working with [R](https://www.r-project.org/), [R Studio](https://www.rstudio.com/) and the [tidyverse packages](https://www.tidyverse.org/). If you feel like it, you can visit those links and install R and R Studio on your laptops (but we will do this together in class as well!). That being said, for this course you need a **laptop**, **R** and **R Studio**, a **web browser**, and a **spreadsheet editor** such as Excel might come in handy but is not required (NotePad works too).

I also recommend **two books** to serve as a reference guides. The first one is called [R for Data Science](https://r4ds.had.co.nz/) and the second one is [Hands-On Programming with R](https://rstudio-education.github.io/hopr/). You can read both books online for free, or purchase a hard-copy from Amazon if you prefer.

On March 15, I will upload all course material for the respective days (see navigation pane above).

As of now, I am planning to cover the following topics (but I am flexible and can adapt to the needs of you guys!):

## Course Overview 

### Friday (Day 1)

- Intro to [R](https://www.r-project.org/) (Downloading R, Getting to know R, R Scripts, Data structures)

- Intro to [R Studio](https://www.rstudio.com/) (Downloading R Studio, Exploring R Studio)

- General introduction to [statistics](https://en.wikipedia.org/wiki/Statistics)

    - [Descriptive statistics](https://en.wikipedia.org/wiki/Descriptive_statistics)

    - [Probability distributions](https://en.wikipedia.org/wiki/Probability_distribution) ([binomial](https://en.wikipedia.org/wiki/Binomial_distribution), [Poisson](https://en.wikipedia.org/wiki/Poisson_distribution), [normal](https://en.wikipedia.org/wiki/Normal_distribution))

    - [Inferential statistics](https://en.wikipedia.org/wiki/Statistical_inference)

    - [Statistical assumptions](https://en.wikipedia.org/wiki/Statistical_assumption)


### Saturday (Day 2)

- Intro to the [*tidyverse*](https://www.tidyverse.org/) packages

- [Reading](https://readr.tidyverse.org/) and creating tidy data using the [*tidyr*](https://tidyr.tidyverse.org/)  package

- Data manipulation using the [*dplyr*](https://dplyr.tidyverse.org/) package

- Data visualization using the [*ggplot2*](https://ggplot2.tidyverse.org/) package

- Basic statistical analyses

    - [Correlation](https://en.wikipedia.org/wiki/Correlation_and_dependence)

    - [Linear regression](https://en.wikipedia.org/wiki/Linear_regression)

    - [Analysis of variance](https://en.wikipedia.org/wiki/Analysis_of_variance)

    - [Generalized linear models](https://en.wikipedia.org/wiki/Generalized_linear_model)

- Producing tidy model outputs using the [*broom*](https://cran.r-project.org/web/packages/broom/vignettes/broom.html) package


### Day 3(Sunday)

- Presenting your results using [R Studio](https://www.rstudio.com/) and [R Markdown](https://rmarkdown.rstudio.com/)

- Your turn! Pick a dataset (your own, or an R dataset), read it into R, wrangle it, visualize it, model it, communicate it.

- General trouble shooting


# See you soon!
